# variables
TICK_DELAY = 100   # highest tested is 75 @zeller
RPM = 2400
UP_SCAN = 0.95
LOW_SCAN = 0.35


# calculate
STEPSPERMM = 76.2
CPU_SPEED = 200E6
FACETS = 4
TICKS_PER_MIRROR_SEGMENT = round(CPU_SPEED//(TICK_DELAY*(RPM*FACETS)/60))
TICKS_START = LOW_SCAN*TICKS_PER_MIRROR_SEGMENT
TICKS_END = UP_SCAN*TICKS_PER_MIRROR_SEGMENT
SCANLINE_DATA_SIZE = round((TICKS_END-TICKS_START)//8)
print("TICKS_PER_MIRROR_SEGMENT {}".format(TICKS_PER_MIRROR_SEGMENT))
print("TICKS_START {}".format(TICKS_START))
print("TICKS_END {}".format(TICKS_END))
print("SCANLINE_DATA_SIZE {}".format(SCANLINE_DATA_SIZE))
print("FACET SCANLINE SIZE {}".format(TICKS_PER_MIRROR_SEGMENT//8))
SPINUP_TICKS = 1.5*CPU_SPEED/TICK_DELAY
MAX_WAIT_STABLE_TICKS = 1.125*CPU_SPEED/TICK_DELAY
END_OF_DATA_WAIT_TICKS = 0.75*CPU_SPEED/TICK_DELAY
print("SPINUP_TICKS {}".format(SPINUP_TICKS))
print("MAX_WAIT_STABLE_TICKS {}".format(MAX_WAIT_STABLE_TICKS))
print("END_OF_DATA_WAIT_TICKS {}".format(END_OF_DATA_WAIT_TICKS))

SLED_SPEED = 1/STEPSPERMM*(RPM*FACETS/60)
print("Sled speed is fixed at {} mm/s".format(SLED_SPEED))
print("Laser freq is {} Hz".format(200e6/TICK_DELAY))
