# variables
TICK_DELAY = 75
RPM = 2400
UP_SCAN = 0.8
LOW_SCAN = 0.2


# calculate
CPU_SPEED = 200E6
FACETS = 4
TICKS_PER_MIRROR_SEGMENT = round(CPU_SPEED//(TICK_DELAY*(RPM*FACETS)/60))
TICKS_START = 0.2*TICKS_PER_MIRROR_SEGMENT
TICKS_END = 0.8*TICKS_PER_MIRROR_SEGMENT
SCANLINE_DATA_SIZE = round((TICKS_END-TICKS_START)//8)
print("TICKS_PER_MIRROR_SEGMENT {}".format(TICKS_PER_MIRROR_SEGMENT))
print("TICKS_START {}".format(TICKS_START))
print("TICKS_END {}".format(TICKS_END))
print("SCANLINE_DATA_SIZE {}".format(SCANLINE_DATA_SIZE))
#
SPINUP_TICKS = 1.5*CPU_SPEED/TICK_DELAY
MAX_WAIT_STABLE_TICKS = 1.125*CPU_SPEED/TICK_DELAY
END_OF_DATA_WAIT_TICKS = 0.75*CPU_SPEED/TICK_DELAY
print("SPINUP_TICKS {}".format(SPINUP_TICKS))
print("MAX_WAIT_STABLE_TICKS {}".format(MAX_WAIT_STABLE_TICKS))
print("END_OF_DATA_WAIT_TICKS {}".format(END_OF_DATA_WAIT_TICKS))


